spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.INDENT_OUTPUT=true

spring.datasource.url=jdbc:mysql://mysql-db:3306/post
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=validate
#spring.datasource.hikari.maximum-pool-size=20

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

management.endpoints.web.exposure.include=*
management.metrics.distribution.percentiles-histogram.http.server.requests=true
spring.application.name=ejem0-employee
